# Generated by Django 3.1.3 on 2020-11-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('over', '0005_remove_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
